---
- hosts: @vm_name@
  vars:
    #---- postgres ---------------
    docker_compose_version: 1.21.2
    ant_version: 1.9.3
    maven_version: 3.3.1
    #scala_version: 2.10.3
    scala_version: 2.11.5
    sbt_version: "0.13.8"
    # intellij_version: 14.1
    netbeans_version: 8.0.2
    locale: en_US.UTF-8
    postgresql:
      version: 9.6
      repo: 'deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'
      install_development_headers: true

      pg_username: postgres
      pg_password: postgres

      user: postgres
      group: postgres

      config:
        shared_buffers: 24MB
        work_mem: 1MB

        checkpoint_segments: 3
        checkpoint_completion_target: 0.5

        effective_cache_size: 128MB
    #---- ruby ---------------
    #ruby: ruby-1.9.2-p180
    ruby_version: 2.1.3
    rbenv_makeopts: ""
    phantomjs: phantomjs-2.1.1-linux-x86_64
    dev_db: dev
    test_db: test
    deploy: vagrant
    virtualbox_url: http://download.virtualbox.org/virtualbox/4.3.10/virtualbox-4.3_4.3.10-93012~Ubuntu~raring_amd64.deb
    virtualbox_deb_package: /tmp/virtualbox.deb
    #--ansible-redis
    with_redmon: False
  roles:
    - { role: '@ansible_roles_path@apt', sudo: true }
    - { role: '@ansible_roles_path@git', sudo: true }
    # - { role: '@ansible_roles_path@docker_ubuntu_14' }
    # - { role: '@ansible_roles_path@docker_ubuntu_16' }
    # - { role: '@ansible_roles_path@ngrok' }
    
    # check https://github.com/rvm/rvm1-ansible as alternative

    # --------- ruby ----------------------------------------
    # - { role: '@ansible_roles_path@rbenv', sudo: false }
    # - { role: '@ansible_roles_path@ruby',  sudo: false }

    # --------- java ----------------------------------------
    # - { role: '@ansible_roles_path@jdk8' }
    # - { role: '@ansible_roles_path@jdk7' }
    # - { role: '@ansible_roles_path@maven' }

    # --------- clojure ----------------------------------------
    # - { role: '@ansible_roles_path@leiningen' }

    # --------- node.js ----------------------------------------
    # - { role: '@ansible_roles_path@node' }
    # - { role: '@ansible_roles_path@node-4x' }
    # - { role: '@ansible_roles_path@node-5x' }
    # - { role: '@ansible_roles_path@node-7x' }
    # - { role: '@ansible_roles_path@node-8x' }
    # - { role: '@ansible_roles_path@bower' }
    # - { role: '@ansible_roles_path@gulp' }
    # - { role: '@ansible_roles_path@npm_upgrade' }

    # --------- erlang ----------------------------------------
    # - { role: '@ansible_roles_path@erlang' }
    # - { role: '@ansible_roles_path@elixir' }

    # --------- go ----------------------------------------
    # - { role: '@ansible_roles_path@go' }

    # --------- DB ----------------------------------------
    # - { role: '@ansible_roles_path@postgres' }
    # - { role: '@ansible_roles_path@pgadmin3' }
    # - { role: '@ansible_roles_path@pgadmin4' }
    # - { role: '@ansible_roles_path@pgadmin3_ubuntu16' }
    # - { role: '@ansible_roles_path@mongo' }
    # - { role: '@ansible_roles_path@mysql' }
    # - { role: '@ansible_roles_path@mysql-workbench' }
    # - { role: '@ansible_roles_path@cassandra' }

    # - { role: '@ansible_roles_path@Stouts.elasticsearch' }
    # - { role: '@ansible_roles_path@ansible-redis' }
    # - { role: '@ansible_roles_path@scala' }
    # - { role: '@ansible_roles_path@sbt' }

    # --------- editors ----------------------------------------
    # - { role: '@ansible_roles_path@sublime' }
    # - { role: '@ansible_roles_path@intellij' }
    # - { role: '@ansible_roles_path@rubymine' }
    # - { role: '@ansible_roles_path@neovim' }
    # - { role: '@ansible_roles_path@netbeans' }

    # - { role: '@ansible_roles_path@chrome' }

    # - { role: '@ansible_roles_path@phantomjs' } 

  # tasks:
  #   - name: make sure the system encoding is utf-8
  #     sudo: yes
  #     template: src=provisioning/provision/templates/locale dest=/etc/default/locale
  #               owner=root group=root mode=644

    # - include: 'provisioning/provision/tasks/svn.yml'

  # handlers:
  #   - include: 'provisioning/provision/handlers/restart_mysql.yml'
