---
- hosts: starter
  vars:
    #---- postgres ---------------
    ant_version: 1.9.3
    maven_version: 3.3.1
    #scala_version: 2.10.3
    scala_version: 2.11.5
    sbt_version: "0.13.8"
    intellij_version: 14.1
    netbeans_version: 8.0.2
    locale: en_US.UTF-8
    postgresql:
      version: 9.5
      repo: 'deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'
      install_development_headers: true

      pg_username: postgres
      pg_password: postgres

      user: postgres
      group: postgres

      config:
        shared_buffers: 24MB
        work_mem: 1MB

        checkpoint_segments: 3
        checkpoint_completion_target: 0.5

        effective_cache_size: 128MB
    #---- ruby ---------------   
    #ruby: ruby-1.9.2-p180
    ruby_version: 2.1.3
    rbenv_makeopts: ""
    phantomjs: phantomjs-1.9.0-linux-x86_64
    dev_db: dev
    test_db: test
    deploy: vagrant
    virtualbox_url: http://download.virtualbox.org/virtualbox/4.3.10/virtualbox-4.3_4.3.10-93012~Ubuntu~raring_amd64.deb
    virtualbox_deb_package: /tmp/virtualbox.deb
    #--ansible-redis
    with_redmon: False
  roles:
    # check https://github.com/rvm/rvm1-ansible as alternative
    # - { role: 'provisioning/provision/roles/rbenv', sudo: false }
    # - { role: 'provisioning/provision/roles/ruby',  sudo: false }
    # - { role: 'provisioning/provision/roles/postgres'}
    # - { role: 'provisioning/provision/roles/cassandra}
    # - { role: 'provisioning/provision/roles/Stouts.elasticsearch'} 
    # - { role: 'provisioning/provision/roles/ansible-redis'}
    # - { role: 'provisioning/provision/roles/scala'}
    # - { role: 'provisioning/provision/roles/sbt'}
    # - { role: 'provisioning/provision/roles/intellij'}


  tasks:
    - name: make sure the system encoding is utf-8
      sudo: yes
      template: src=provisioning/provision/templates/locale dest=/etc/default/locale
                owner=root group=root mode=644

    - include: 'provisioning/provision/tasks/apt.yml'
    # - include: 'provisioning/provision/tasks/svn.yml'
    #---- db
    # - include: 'provisioning/provision/tasks/pgadmin3.yml'
    # - include: 'provisioning/provision/tasks/mysql.yml'
    # - include: 'provisioning/provision/tasks/mysql-workbench.yml'
    # - include: 'provisioning/provision/tasks/mongo.yml'

    # - include: 'provisioning/provision/tasks/phantomjs.yml'


    # - include: 'provisioning/provision/tasks/jdk7.yml'
    # - include: 'provisioning/provision/tasks/jdk8.yml'
    # require java installed
    # - include: 'provisioning/provision/tasks/maven.yml'
    # - include: 'provisioning/provision/tasks/leiningen.yml'
    #---- js development
    # - include: 'provisioning/provision/tasks/node.yml'
    # - include: 'provisioning/provision/tasks/node_4x.yml'
    # - include: 'provisioning/provision/tasks/node_5x.yml'
    # - include: 'provisioning/provision/tasks/bower.yml'
    # - include: 'provisioning/provision/tasks/gulp.yml'

    # require java installed
    # editors
    # - include: 'provisioning/provision/tasks/sublime.yml'
    # - include: 'provisioning/provision/tasks/netbeans.yml'

    # - include: 'provisioning/provision/tasks/chrome.yml'
  # handlers:
  #   - include: 'provisioning/provision/handlers/restart_mysql.yml'
