---
- hosts: starter
  vars:
    #---- postgres ---------------
    ant_version: 1.9.3
    maven_version: 3.3.1
    #scala_version: 2.10.3
    scala_version: 2.11.5
    sbt_version: "0.13.8"
    intellij_version: 14.1
    netbeans_version: 8.0.2
    locale: en_US.UTF-8
    postgresql:
      version: 9.5
      repo: 'deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'
      install_development_headers: true

      pg_username: postgres
      pg_password: postgres

      user: postgres
      group: postgres

      config:
        shared_buffers: 24MB
        work_mem: 1MB

        checkpoint_segments: 3
        checkpoint_completion_target: 0.5

        effective_cache_size: 128MB
    #---- ruby ---------------
    #ruby: ruby-1.9.2-p180
    ruby_version: 2.1.3
    rbenv_makeopts: ""
    phantomjs: phantomjs-1.9.0-linux-x86_64
    dev_db: dev
    test_db: test
    deploy: vagrant
    virtualbox_url: http://download.virtualbox.org/virtualbox/4.3.10/virtualbox-4.3_4.3.10-93012~Ubuntu~raring_amd64.deb
    virtualbox_deb_package: /tmp/virtualbox.deb
    #--ansible-redis
    with_redmon: False
  roles:
    - { role: 'provisioning/provision/roles/apt', sudo: true }
    - { role: 'provisioning/provision/roles/git', sudo: true }
    # check https://github.com/rvm/rvm1-ansible as alternative

    # --------- ruby ----------------------------------------
    # - { role: 'provisioning/provision/roles/rbenv', sudo: false }
    # - { role: 'provisioning/provision/roles/ruby',  sudo: false }

    # --------- java ----------------------------------------
    # - { role: 'provisioning/provision/roles/jdk8' }
    # - { role: 'provisioning/provision/roles/jdk7' }
    # - { role: 'provisioning/provision/roles/maven' }

    # --------- clojure ----------------------------------------
    # - { role: 'provisioning/provision/roles/leiningen' }

    # --------- node.js ----------------------------------------
    # - { role: 'provisioning/provision/roles/node' }
    # - { role: 'provisioning/provision/roles/node-4x' }
    # - { role: 'provisioning/provision/roles/node-5x' }
    # - { role: 'provisioning/provision/roles/bower' }
    # - { role: 'provisioning/provision/roles/gulp' }
    # - { role: 'provisioning/provision/roles/npm_upgrade' }

    # --------- erlang ----------------------------------------
    # - { role: 'provisioning/provision/roles/erlang' }
    # - { role: 'provisioning/provision/roles/elixir' }

    # --------- DB ----------------------------------------
    # - { role: 'provisioning/provision/roles/postgres' }
    # - { role: 'provisioning/provision/roles/pgadmin3' }
    # - { role: 'provisioning/provision/roles/mongo' }
    # - { role: 'provisioning/provision/roles/mysql' }
    # - { role: 'provisioning/provision/roles/mysql-workbench' }
    # - { role: 'provisioning/provision/roles/cassandra' }

    # - { role: 'provisioning/provision/roles/Stouts.elasticsearch' }
    # - { role: 'provisioning/provision/roles/ansible-redis' }
    # - { role: 'provisioning/provision/roles/scala' }
    # - { role: 'provisioning/provision/roles/sbt' }

    # --------- editors ----------------------------------------
    # - { role: 'provisioning/provision/roles/sublime' }
    # - { role: 'provisioning/provision/roles/intellij' }
    # - { role: 'provisioning/provision/roles/rubymine' }
    # - { role: 'provisioning/provision/roles/netbeans' }

    # - { role: 'provisioning/provision/roles/chrome' }

    # - { role: 'provisioning/provision/roles/phantomjs' }

  tasks:
    - name: make sure the system encoding is utf-8
      sudo: yes
      template: src=provisioning/provision/templates/locale dest=/etc/default/locale
                owner=root group=root mode=644

    # - include: 'provisioning/provision/tasks/svn.yml'

  # handlers:
  #   - include: 'provisioning/provision/handlers/restart_mysql.yml'
