---
go_tarball: "go1.14.1.linux-amd64.tar.gz"
go_tarball_checksum: "sha256:2f49eb17ce8b48c680cdb166ffd7389702c0dec6effa090c324804a5cac8a7f8"
go_version_target: "go version go1.9.5 linux/amd64"
set_go_path: true
