---
# nice example http://cn.soulmachine.me/blog/20140129/
- name: Maven | Download v 3.6.0 into /opt/maven3.tar.gz
  sudo: yes
  get_url: dest=/opt/maven3.tar.gz url=http://ftp.man.poznan.pl/apache/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz

- name: Maven | Upack from /opt/maven3.tar.gz
  sudo: yes
  action: command creates=/opt/apache-maven-3.6.0 chdir=/opt tar zxvf /opt/maven3.tar.gz

- name: Maven | unpacked maven exists?
  sudo: yes
  stat: path=/opt/apache-maven-3.6.0
  register: maven_unpacked_exists

- name: Maven | Rename to /opt/maven
  sudo: yes
  command: creates="/opt/maven" mv /opt/apache-maven-3.6.0 /opt/maven
  when: maven_unpacked_exists.stat.exists

# - name: Maven | Move to /usr/local/maven
#   sudo: yes
#   command: creates="/usr/local/share" mv /opt/maven /usr/local/share
#   when: maven_unpacked_exists.stat.exists

# - name:  Maven | Add to ~/.bash_profile
#   lineinfile: dest=~{{deploy}}/.bash_profile regexp='^#?\s*export M2_HOME=(.*)$' line='export M2_HOME=/usr/local/maven' state=present
#   lineinfile: dest=~{{deploy}}/.bash_profile regexp='^#?\s*export M2=(.*)$' line='export M2=\$M2_HOME/bin' state=present
#   lineinfile: dest=~{{deploy}}/.bash_profile regexp='^#?\s*export PATH=(.*)M2(.*)$' line="export PATH=\$M2:\$PATH" state=present
#   lineinfile: dest=~{{deploy}}/.bash_profile regexp='^#?\s*export MAVEN_OPTS=(.*)$' line="export MAVEN_OPTS='-Xms256m -Xmx512m'" state=present

# - name: Maven | exists /usr/local/share/maven?
#   stat: path=/opt/maven
#   register: maven_local_exists

- name: Maven | link exists?
  sudo: yes
  stat: path=/usr/bin/mvn
  register: maven_link_exists

- name: Maven | Assign link
  sudo: yes
  command: sudo ln -s /opt/maven/bin/mvn /usr/bin/mvn
  when: not maven_link_exists.stat.exists


# export PATH=/usr/bin:/bin when problems with console
# - lineinfile: dest=~{{deploy}}/.bashrc regexp='^#?\s*export M2_HOME=(.*)$' line='export M2_HOME=/usr/local/share/maven' state=present

# - lineinfile: dest=~{{deploy}}/.bashrc regexp='^#?\s*export M2=(.*)$' line='export M2=\$M2_HOME/bin' state=present

# - lineinfile: dest=~{{deploy}}/.bashrc regexp='^#?\s*export PATH=(.*)M2(.*)$' line="export PATH=\$M2:\$PATH" state=present

# - lineinfile: dest=~{{deploy}}/.bashrc regexp='^#?\s*export MAVEN_OPTS=(.*)$' line="export MAVEN_OPTS='-Xms256m -Xmx512m'" state=present
