---
- name: Install python deps
  apt: name={{ item }} state=latest
  with_items:
    - python-dev
    - python-pip
    - python3-dev

- name: Install ppa repository
  sudo: yes
  action: apt_repository repo=ppa:neovim-ppa/unstable

- name: Install neovim
  sudo: yes
  apt: pkg=neovim state=latest update_cache=yes force=yes
