---
- name: Add postgresql to sources list
  become: yes
  become_method: sudo
  copy:
    content: "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main"
    dest: /etc/apt/sources.list.d/pgdg.list

- name: Add postgres repo key
  become: yes
  become_method: sudo
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Apt install pgadmin3
  become: yes
  become_method: sudo
  apt:
    name: pgadmin3
    state: latest
    update_cache: yes
