---
galaxy_info:
  author: "Daniel Perez"
  company: "Claude Tech"
  license: MIT
  min_ansible_version: 1.4
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  categories:
    - programming
dependencies: []
